# this yml file will run when cpu utilisation is above threshold

- name: Patch the incident 
  uri:
    url: "{{snow_patch_url}}"
    method: Patch
    user: "{{snow_user}}"
    password: "{{snow_pass}}"
    #body: '{"work_notes":"cpu utilization is Above threshold", "state": "In Progress"}'
    body: '{"work_notes":"cpu utilization is Above threshold"}'
    return_content: true
    status_code: 200
    body_format: json